

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';


export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION= 'CERRAR_SESION';

export const AGREGAR_CLIENTE = 'AGREGAR_CLIENTE';
export const OBTENER_CLIENTE = 'OBTENER_CLIENTE'

export const AGREGAR_FUNCIONARIO = 'AGREGAR_FUNCIONARIO';
export const OBTENER_FUNCIONARIO = 'OBTENER_FUNCIONARIO';

export const AGREGAR_CONTRATO = 'AGREGAR_CONTRATO';